site_name: Open App Hack Documentation

repo_url: https://github.com/WiproOpenSourcePractice/openhack-vm.git
site_description: 'OpenApphack-VM - A VM for Openhack development, built with Vagrant + Ansible'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
