site_name: OpenApp Hack Documentation

repo_url: https://github.com/WiproOpenSourcePractice/openapphack-vm.git
site_description: 'OpenApphack-VM - A VM for OpenApphack development, built with Vagrant + Ansible'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
